export const projects = [
  {
    id: 1,
    title: "Plinko Aventura Marina",
    description: "Un tablero temático con diseño marino, perfecto para centros de entretenimiento familiar.",
    image: "/marina.png",
    category: "Temático",
    year: "2025",
    month: "Enero",
    client: "AquaPark Barcelona",
    features: [
      "Diseño marino con elementos acuáticos",
      "Materiales resistentes al agua",
      "Iluminación LED integrada",
      "Sonidos temáticos del océano",
    ],

  },
  {
    id: 2,
    title: "Plinko Educativo Matemático",
    description: "Tablero diseñado para enseñar conceptos matemáticos de forma divertida.",
    image: "/mate.png",
    category: "Educativo",
    year: "2025",
    month: "Febrero",
    client: "Colegio Internacional Madrid",
    features: [
      "Números y operaciones matemáticas",
      "Materiales educativos certificados",
      "Guía didáctica incluida",
      "Adaptable a diferentes edades",
    ],

  },
  {
    id: 3,
    title: "Plinko Premium",
    description: "Tablero de alta gama para establecimientos de entretenimiento premium.",
    image: "/prem.png",
    category: "Profesional",
    year: "2025",
    month: "Marzo",
    client: "Centro de Entretenimiento Valencia",
    features: [
      "Acabados de lujo en madera noble",
      "Sistema de puntuación digital",
      "Iluminación profesional",
      "Garantía extendida de 5 años",
    ],
  },
  {
    id: 4,
    title: "Plinko Espacial",
    description: "Aventura cósmica con un tablero inspirado en el espacio exterior.",
    image: "/boto.png",
    category: "Temático",
    year: "2025",
    month: "Abril",
    client: "Museo de Ciencias Sevilla",
    features: [
      "Tema espacial con planetas y estrellas",
      "Efectos de sonido cósmicos",
      "Materiales fosforescentes",
      "Experiencia inmersiva 360°",
    ],

  },
  {
    id: 5,
    title: "Plinko Jardín Botánico",
    description: "Tablero inspirado en la naturaleza con elementos orgánicos y sostenibles.",
    image: "/botamic.png",
    category: "Temático",
    year: "2025",
    month: "Mayo",
    client: "Jardín Botánico de Barcelona",
    features: [
      "Materiales ecológicos y sostenibles",
      "Diseño inspirado en plantas y flores",
      "Sonidos de la naturaleza",
      "Certificación medioambiental",
    ],
  },
  {
    id: 6,
    title: "Plinko Retro Arcade",
    description: "Un homenaje a los juegos clásicos con estética vintage y moderna funcionalidad.",
    image: "/retro.png",
    category: "Clásico",
    year: "2025",
    month: "Enero",
    client: "Arcade Retro Madrid",
    features: [
      "Estética vintage de los años 80",
      "Luces LED programables",
      "Sonidos clásicos de arcade",
      "Materiales duraderos premium",
    ],
  },
]
